version: 2

updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  labels:
    - "dependencies"
    - "php"
  open-pull-requests-limit: 10

- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
  labels:
    - "dependencies"
    - "submodules"
  open-pull-requests-limit: 10
